### ISSUE TITLE
Counters show error data due to the api changes

### ISSUE THREAD

**Issue by laserdark** [veigr/EventMapHpViewer#3]
The api of map-hp has possibly been changed during last patch which released one two-phases map 7-2, as shown below.
plz have a look on it.
![BUG](https://img.nga.178.com/attachments/mon_201811/16/-4ada3Q5-l027K12T1kShh-8j.png)

**Comment by veigr** [comment]
恐らく 3.4.1 で対応できたと思います。
ご確認ください。
https://github.com/veigr/EventMapHpViewer/releases/tag/v3.4.1
